// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using RootNamespace.Repository;

#nullable disable

namespace RootNamespace.Migrations
{
    [DbContext(typeof(ModuleNameContext))]
    partial class ModuleNameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("RootNamespace.Models.ModuleName", b =>
            {
                b.Property<int>("ModuleNameId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("CreatedBy")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<DateTime>("CreatedOn")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<int>("ModuleId")
                    .HasColumnType("int");

                b.Property<string>("ModifiedBy")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<DateTime>("ModifiedOn")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("ModuleNameId");

                b.ToTable("RootNamespaceModuleName");
            });
#pragma warning restore 612, 618
        }
    }
}
